### ISSUE TITLE
ul / li are KO

### ISSUE THREAD

**Issue by Max84** [henck/rtf-html-php#12]
Hi, 

this is a RTF sample:

{\rtf1\ansi\ansicpg1252\deff0\deflang1036{\fonttbl{\f0\fnil\fcharset0 Microsoft Sans Serif;}{\f1\fnil\fcharset2 Symbol;}}
                {\colortbl ;\red0\green0\blue0;}
                \viewkind4\uc1\pard\f0\fs17 SAUT DE LIGNE\par
                SAUT DE LIGNE\par
                \b GRAS\b0
                \i ITALIQUE\i0  \ul SOULIGNE \cf1\ulnone\strike BARRE\cf0\strike0\par
                \pard{\pntext\f1\'B7\tab}{*\pn\pnlvlblt\pnf1\pnindent0{\pntxtb\'B7}}PUCE\par
                {\pntext\f1\'B7\tab}PUCE\par
                {\pntext\f1\'B7\tab}PUCE\par
                \pard\ul\b\i\strike MELANGE\par
                \par
                \par
                \pard{\pntext\f1\'B7\tab}{*\pn\pnlvlblt\pnf1\pnindent0{\pntxtb\'B7}}\cf1\ulnone\b0\i0\strike0 bla bla test\par
                {\pntext\f1\'B7\tab}essai\cf0\par
                }

Before each "PUCE", i should get an <li> tag or a span bullet.

Great tools :)

**Comment by henck** [comment]
There is some support for bullets. Please note that RTF does not implement a bullet control code. Instead, it uses a character followed by a tab (at least, Wordpad produces this). In your code, it's this part:

    \f1'B7\tab

Here, the font is set to font 1 from the font table, which is the Symbol font (browser support may not be available). It then outputs character B7 (a small dot in ASCII), followed by a tab. We render a tab as a series of `&nbsp;` characters, so the spacing between the dot and the text will be big.

Since tabs don't really exist in HTML, it may be better to converts tabs to just a single space.
