### ISSUE TITLE
Please extend the parser with text alignment, font color and images

### ISSUE THREAD

**Issue by kschroeer** [henck/rtf-html-php#34]
Hi,

let me say first of all that you have done a great job. A nice little tool and it works without external services. I think that's really good!

You write that your parser only interprets the bare essentials that you need on a website. I agree with that as well.
What I would still miss, because I just use it frequently on websites, would be the following things:
* Text alignment (left-aligned, centered, right-aligned).
* Background and font color (I use it for example to highlight individual text passages).
* Images (can easily be embedded as a binary string directly into the img tag).

Maybe you could think again about expanding your parser accordingly.

Greetz

**Comment by mhtamala** [comment]
At your request background and font color is now supported.
best regards

**Comment by bretto36** [comment]
I'm having problems with this one. I get a missing parameter issue as it misaligns the colours in the group and tries to do green blue blank. Instead of red green blue

`{\\rtf1\\deff0{\\fonttbl{\\f0 Times New Roman;}{\\f1 MS Sans Serif;}}{\\colortbl\\red0\\green0\\blue0 ;\\red0\\green0\\blue255 ;}{\\*\\defchp \\f1\\fs20}{\\*\\listoverridetable}{\\stylesheet {\\ql\\f1\\fs20\\cf0 Normal;}{\\*\\cs1\\f1\\fs20\\cf0 Default Paragraph Font;}{\\*\\cs2\\sbasedon1\\f1\\fs20\\cf0 Line Number;}{\\*\\cs3\\ul\\f1\\fs20\\cf1 Hyperlink;}}\\splytwnine\\htmautsp\\sectd\\pard\\plain\\ql{\\b\\f1\\fs20\\cf0 Disbursements}\\b\\f1\\fs20\\cf0\\par\\pard\\plain\\ql{\\f1\\fs20\\cf0 As per contractual agreement.}\\f1\\fs20\\cf0\\par}`

**Comment by mhtamala** [comment]
Hi bretto36, sorry to know about this inconvenience. The actual RTF parser is written according to RTF specification 1.5 please see [link](http://www.biblioscape.com/rtf15_spec.htm#Heading16). important to know is that each definition in the color table group must be delimited by a semicolon, even if the definition is omitted.
Your piece of rtf code does not conform to RTF specifications. to make it standard please add a semicolon after `\colortbl`.
your workaround code although making your file parse correctly it does make other standard RTF files behave wrongly.
best regards

**Comment by mhtamala** [comment]
@bretto36 
thanks for reporting this issue.
it's an error that occur exclusively when the the default color is explicitly defined. In most cases it is omitted from definition.
I managed to fix this issue please [try it](https://github.com/mhtamala/rtf-html-php/blob/f8d61c981476a70a7836668c2198c7c694b0b36f/rtf-html-php.php) and report on
thanks for making it a better RTF parser
best regards
